services:
  pytorch-cifar10:
    build: .
    container_name: pytorch-cifar10
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
    stdin_open: true
    tty: true
    shm_size: '4gb'
